export interface Theme {
  id: string;
  name: string;
  emoji: string;
  color: string;
  imgs: string[];
  frontMsg: string; // default short front-of-card message
}

export interface CardMessage {
  name: string;
  msg: string;
  gift?: number;
  hw?: boolean;
  photoData?: string;
  timestamp?: string;
}

export const THEMES: Theme[] = [
  {
    id: "thankyou",
    name: "Thank you",
    emoji: "💛",
    color: "linear-gradient(160deg,#1a4a5a,#2d7d8f)",
    frontMsg: "Thank you so much!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/thank_you/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/thank_you/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/thank_you/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/thank_you/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/thank_you/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/thank_you/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/thank_you/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/thank_you/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/thank_you/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/thank_you/card_10.png",
    ],
  },
  {
    id: "birthday",
    name: "Birthday",
    emoji: "🎂",
    color: "linear-gradient(135deg,#D94E7A,#F9A8D4)",
    frontMsg: "Happy Birthday!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/birthday/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/birthday/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/birthday/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/birthday/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/birthday/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/birthday/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/birthday/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/birthday/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/birthday/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/birthday/card_10.png",
    ],
  },
  {
    id: "18th-birthday",
    name: "18th Birthday",
    emoji: "🎉",
    color: "linear-gradient(135deg,#7C3AED,#F472B6)",
    frontMsg: "Happy 18th!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/18th_birthday/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/18th_birthday/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/18th_birthday/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/18th_birthday/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/18th_birthday/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/18th_birthday/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/18th_birthday/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/18th_birthday/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/18th_birthday/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/18th_birthday/card_10.png",
    ],
  },
  {
    id: "kids-birthday",
    name: "Kids Birthday",
    emoji: "🎈",
    color: "linear-gradient(135deg,#F472B6,#60A5FA)",
    frontMsg: "Happy Birthday!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_birthday/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_birthday/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_birthday/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_birthday/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_birthday/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_birthday/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_birthday/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_birthday/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_birthday/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_birthday/card_10.png",
    ],
  },
  {
    id: "cars",
    name: "Cars",
    emoji: "🚗",
    color: "linear-gradient(135deg,#1a1a2e,#e94560)",
    frontMsg: "You're a legend!",
    imgs: [
      "/vw-mk1.jpg",
      "/vw-mk2.jpg",
      "/vw-corrado.jpg",
    ],
  },
  {
    id: "dad",
    name: "Dad",
    emoji: "👨",
    color: "linear-gradient(135deg,#1B4332,#52B788)",
    frontMsg: "Thanks Dad!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/dad/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/dad/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/dad/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/dad/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/dad/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/dad/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/dad/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/dad/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/dad/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/dad/card_10.png",
    ],
  },
  {
    id: "grandad",
    name: "Grandad",
    emoji: "👴",
    color: "linear-gradient(135deg,#3A5A40,#A3B18A)",
    frontMsg: "Thanks Grandad!",
    imgs: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1459865264687-595d652de67e?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "mum",
    name: "Mum",
    emoji: "👩",
    color: "linear-gradient(135deg,#D94E7A,#FECDD3)",
    frontMsg: "Thanks Mum!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mum/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mum/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mum/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mum/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mum/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mum/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mum/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mum/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mum/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mum/card_10.png",
    ],
  },
  {
    id: "grandmother",
    name: "Grandmother",
    emoji: "👵",
    color: "linear-gradient(135deg,#7C5CBF,#E9D5FF)",
    frontMsg: "Thanks Grandma!",
    imgs: [
      "https://images.unsplash.com/photo-1455582916367-25f75bfc6710?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1468581264429-2548ef9eb732?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "mates",
    name: "Mates",
    emoji: "🍺",
    color: "linear-gradient(135deg,#C9933A,#F59E0B)",
    frontMsg: "Cheers Buddy!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mates/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mates/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mates/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mates/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mates/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mates/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mates/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mates/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mates/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/mates/card_10.png",
    ],
  },
  {
    id: "baby",
    name: "New Baby",
    emoji: "👶",
    color: "linear-gradient(135deg,#93C5FD,#DDD6FE)",
    frontMsg: "Congratulations!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/baby/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/baby/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/baby/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/baby/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/baby/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/baby/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/baby/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/baby/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/baby/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/baby/card_10.png",
    ],
  },
  {
    id: "wedding",
    name: "Wedding",
    emoji: "💍",
    color: "linear-gradient(135deg,#B45309,#FDE68A)",
    frontMsg: "Congratulations!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/wedding/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/wedding/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/wedding/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/wedding/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/wedding/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/wedding/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/wedding/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/wedding/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/wedding/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/wedding/card_10.png",
    ],
  },
  {
    id: "engagement",
    name: "Engagement",
    emoji: "💍",
    color: "linear-gradient(135deg,#BE185D,#FBCFE8)",
    frontMsg: "Congratulations!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/engagement/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/engagement/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/engagement/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/engagement/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/engagement/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/engagement/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/engagement/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/engagement/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/engagement/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/engagement/card_10.png",
    ],
  },
  {
    id: "retirement",
    name: "Retirement",
    emoji: "🌅",
    color: "linear-gradient(135deg,#0369A1,#38BDF8)",
    frontMsg: "Happy Retirement!",
    imgs: [
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1476820865390-c52aeebb9891?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "coach",
    name: "Coach",
    emoji: "🏅",
    color: "linear-gradient(135deg,#003087,#C8102E)",
    frontMsg: "Thank you Coach!",
    imgs: [
      "/hero-coach.jpg",
      "/afl-ball.jpg",
      "/afl-mark.jpg",
      "https://images.unsplash.com/photo-1459865264687-595d652de67e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1560090995-01632a28895b?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "leaving",
    name: "Leaving",
    emoji: "👋",
    color: "linear-gradient(135deg,#0F172A,#64748B)",
    frontMsg: "We'll miss you!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/leaving/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/leaving/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/leaving/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/leaving/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/leaving/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/leaving/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/leaving/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/leaving/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/leaving/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/leaving/card_10.png",
    ],
  },
  {
    id: "get-well",
    name: "Get Well",
    emoji: "🌻",
    color: "linear-gradient(135deg,#65A30D,#FDE047)",
    frontMsg: "Get well soon!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/get_well/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/get_well/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/get_well/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/get_well/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/get_well/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/get_well/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/get_well/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/get_well/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/get_well/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/get_well/card_10.png",
    ],
  },
  {
    id: "sympathy",
    name: "Sympathy",
    emoji: "🕊️",
    color: "linear-gradient(135deg,#334155,#94A3B8)",
    frontMsg: "Thinking of you",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/sympathy/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/sympathy/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/sympathy/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/sympathy/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/sympathy/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/sympathy/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/sympathy/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/sympathy/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/sympathy/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/sympathy/card_10.png",
    ],
  },
  {
    id: "for-him",
    name: "For Him",
    emoji: "🎁",
    color: "linear-gradient(135deg,#1E293B,#475569)",
    frontMsg: "Thanks so much!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/for_him/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/for_him/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/for_him/card_03.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/for_him/card_04.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/for_him/card_05.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/for_him/card_06.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/for_him/card_07.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/for_him/card_08.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/for_him/card_09.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/for_him/card_10.png",
    ],
  },
  {
    id: "afl",
    name: "AFL",
    emoji: "🏉",
    color: "linear-gradient(135deg,#1E3A5F,#C8102E)",
    frontMsg: "Go team!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/afl/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/afl/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/afl/card_03.png",
    ],
  },
  {
    id: "kids-afl",
    name: "Junior AFL",
    emoji: "🏉",
    color: "linear-gradient(135deg,#2563EB,#F97316)",
    frontMsg: "Great season!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_afl/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_afl/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/kids_afl/card_03.png",
    ],
  },
  {
    id: "nrl",
    name: "NRL",
    emoji: "🏉",
    color: "linear-gradient(135deg,#1E3A8A,#DC2626)",
    frontMsg: "Go team!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/nrl/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/nrl/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/nrl/card_03.png",
    ],
  },
  {
    id: "rugby-union",
    name: "Rugby Union",
    emoji: "🏉",
    color: "linear-gradient(135deg,#14532D,#CA8A04)",
    frontMsg: "Great game!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/rugby_union/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/rugby_union/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/rugby_union/card_03.png",
    ],
  },
  {
    id: "soccer",
    name: "Soccer",
    emoji: "⚽",
    color: "linear-gradient(135deg,#15803D,#22C55E)",
    frontMsg: "Great season!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/soccer/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/soccer/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/soccer/card_03.png",
    ],
  },
  {
    id: "basketball",
    name: "Basketball",
    emoji: "🏀",
    color: "linear-gradient(135deg,#C2410C,#1F2937)",
    frontMsg: "Nothing but net!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/basketball/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/basketball/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/basketball/card_03.png",
    ],
  },
  {
    id: "netball",
    name: "Netball",
    emoji: "🏐",
    color: "linear-gradient(135deg,#6D28D9,#F9A8D4)",
    frontMsg: "Great season!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/netball/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/netball/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/netball/card_03.png",
    ],
  },
  {
    id: "cricket",
    name: "Cricket",
    emoji: "🏏",
    color: "linear-gradient(135deg,#166534,#BEF264)",
    frontMsg: "Howzat!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/cricket/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/cricket/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/cricket/card_03.png",
    ],
  },
  {
    id: "tennis",
    name: "Tennis",
    emoji: "🎾",
    color: "linear-gradient(135deg,#4D7C0F,#D9F99D)",
    frontMsg: "Great game!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/tennis/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/tennis/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/tennis/card_03.png",
    ],
  },
  {
    id: "golf",
    name: "Golf",
    emoji: "⛳",
    color: "linear-gradient(135deg,#14532D,#84CC16)",
    frontMsg: "Nice one!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/golf/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/golf/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/golf/card_03.png",
    ],
  },
  {
    id: "swimming",
    name: "Swimming",
    emoji: "🏊",
    color: "linear-gradient(135deg,#0284C7,#7DD3FC)",
    frontMsg: "Great swim!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/swimming/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/swimming/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/swimming/card_03.png",
    ],
  },
  {
    id: "surfing",
    name: "Surfing",
    emoji: "🏄",
    color: "linear-gradient(135deg,#0369A1,#22D3EE)",
    frontMsg: "Ride on!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/surfing/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/surfing/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/surfing/card_03.png",
    ],
  },
  {
    id: "cycling",
    name: "Cycling",
    emoji: "🚴",
    color: "linear-gradient(135deg,#0EA5E9,#FACC15)",
    frontMsg: "Great ride!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/cycling/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/cycling/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/cycling/card_03.png",
    ],
  },
  {
    id: "athletics",
    name: "Athletics",
    emoji: "🏃",
    color: "linear-gradient(135deg,#B91C1C,#FBBF24)",
    frontMsg: "You're a champion!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/athletics/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/athletics/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/athletics/card_03.png",
    ],
  },
  {
    id: "boxing",
    name: "Boxing",
    emoji: "🥊",
    color: "linear-gradient(135deg,#7F1D1D,#DC2626)",
    frontMsg: "Champion effort!",
    imgs: [
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/boxing/card_01.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/boxing/card_02.png",
      "https://ofoboqojauitnmdbhcaz.supabase.co/storage/v1/object/public/theme-images/boxing/card_03.png",
    ],
  },
];

export const DEMO_MSGS: CardMessage[] = [
  { name: "Sarah (Liam's mum)", msg: "Thanks for believing in Liam this season! He's loved every game. 🏆", gift: 10, hw: false, timestamp: "5 mins ago" },
  { name: "Michael",            msg: "We couldn't have done it without you! ⭐",                              gift: 20, hw: false, timestamp: "2 hours ago" },
  { name: "James & Kate",       msg: "Best coach we've had — you make every training fun. The kids absolutely adore you and talk about practice all week long.", gift: 20, hw: false, timestamp: "3 hours ago" },
  { name: "The Nguyen family",  msg: "We're so grateful for your patience and dedication.",                   gift: 10, hw: false, timestamp: "Yesterday" },
  { name: "Marcus",             msg: "",                                                                      gift: 7,  hw: true,  timestamp: "Yesterday" },
  { name: "Priya (Asha's mum)", msg: "Asha talks about training every single day. Thank you!",               gift: 0,  hw: false, timestamp: "2 days ago" },
  { name: "Tom & Michelle",     msg: "It's been a privilege watching the kids learn from you.",               gift: 20, hw: false, timestamp: "2 days ago" },
  { name: "Lucy (Charlie's mum)", msg: "Charlie scored his first goal this season and you made it happen.",  gift: 0,  hw: false, timestamp: "3 days ago" },
];

export const PENDING: string[] = [
  "The Williams family",
  "Darren & Sue",
  "Unknown viewer",
  "Unknown viewer",
];
